
#include <opencog/atoms/atom_types/NameServer.h>

using namespace opencog;

Type ANTI_LINK;
Type AT_TIME_LINK;
Type DEFINED_LINGUISTIC_CONCEPT_NODE;
Type DEFINED_LINGUISTIC_RELATIONSHIP_NODE;
Type DOCUMENT_NODE;
Type FEATURE_LINK;
Type FEATURE_NODE;
Type HEBBIAN_LINK;
Type LEMMA_LINK;
Type LEMMA_NODE;
Type LG_CONNECTOR_NODE;
Type PARSE_LINK;
Type PARSE_NODE;
Type PART_OF_SPEECH_LINK;
Type PART_OF_SPEECH_NODE;
Type PREPOSITIONAL_RELATIONSHIP_NODE;
Type REFERENCE_LINK;
Type SEME_NODE;
Type SENTENCE_NODE;
Type TIME_NODE;
Type WORD_INSTANCE_LINK;
Type WORD_INSTANCE_NODE;
Type WORD_NODE;
Type WORD_SENSE_NODE;
