#
# This file reads files that are generated by the OPENCOG_ADD_ATOM_TYPES
# macro so they can be imported using:
#
# from storage_constructors import *
#
# This imports all the python wrappers for atom creation.
#
import warnings

from opencog.atomspace import types, AtomSpace
from opencog.utilities import add_node, add_link

include "opencog/persist/storage/storage_types.pyx"
