flags: {}
packages:
- '.'
extra-deps: []
resolver: lts-8.5
#extra-lib-dirs: [/usr/local/lib/opencog
#                ,/home/roman/OpenCog/atomspace/build/opencog/haskell
#                ]
#

ghc-options:
    opencog-atomspace: -latomspace-cwrapper
