MACRO(OPENCOG_ADD_ATOM_TYPES SCRIPT_FILE HEADER_FILE DEFINITIONS_FILE INHERITANCE_FILE SCM_FILE PYTHON_FILE)
    IF(EXISTS ${CMAKE_SOURCE_DIR}/cmake/OpenCogAtomTypes.cmake)
        SET(OC_ATOM_TYPES_PATH ${CMAKE_SOURCE_DIR}/cmake/OpenCogAtomTypes.cmake)
    ELSE()
        SET(OC_ATOM_TYPES_PATH ${DATADIR}/cmake/OpenCogAtomTypes.cmake)
    ENDIF()
    ADD_CUSTOM_COMMAND (
        COMMAND "${CMAKE_COMMAND}" -DSCRIPT_FILE=\"${CMAKE_CURRENT_SOURCE_DIR}/${SCRIPT_FILE}\" -DHEADER_FILE=\"${CMAKE_CURRENT_BINARY_DIR}/${HEADER_FILE}\" -DDEFINITIONS_FILE=\"${CMAKE_CURRENT_BINARY_DIR}/${DEFINITIONS_FILE}\" -DINHERITANCE_FILE=\"${CMAKE_CURRENT_BINARY_DIR}/${INHERITANCE_FILE}\" -DSCM_FILE=\"${CMAKE_CURRENT_BINARY_DIR}/${SCM_FILE}\" -DPYTHON_FILE=\"${CMAKE_CURRENT_BINARY_DIR}/${PYTHON_FILE}\" -P "${OC_ATOM_TYPES_PATH}"
        OUTPUT  "${CMAKE_CURRENT_BINARY_DIR}/${HEADER_FILE}"
                "${CMAKE_CURRENT_BINARY_DIR}/${DEFINITIONS_FILE}"
                "${CMAKE_CURRENT_BINARY_DIR}/${INHERITANCE_FILE}"
                "${CMAKE_CURRENT_BINARY_DIR}/${SCM_FILE}"
                "${CMAKE_CURRENT_BINARY_DIR}/${PYTHON_FILE}"
        DEPENDS "${SCRIPT_FILE}" "${OC_ATOM_TYPES_PATH}"
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        COMMENT "Generating opencog types"
    )
ENDMACRO(OPENCOG_ADD_ATOM_TYPES SCRIPT_FILE HEADER_FILE DEFINITIONS_FILE INHERITANCE_FILE SCM_FILE PYTHON_FILE)
